version: '3.4'

services:
  web:
    container_name: web
    image: riabov/web:latest
    depends_on:
      - "backend"
    ports:
      - '80:80'
    build:
      context: Tracker.React
      dockerfile: Dockerfile
#      args:
#        NODE_ENV: development
#    env_file: Tracker.React/.env.development
#    environment:
#      NODE_ENV: development
  
  backend:
    image: riabov/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ConnectionStrings__PostgresConnection: server=host.docker.internal; port=5432; database=tracker; username=postgres; password=123123asd@; CommandTimeout=3600
    extra_hosts:
      - "host.docker.internal:host-gateway"  

#  proxy:
#    image: nginx:mainline
#    volumes:
#      - ./Tracker.React/nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "80:80"  
     