version: '3.4'

services:
  web:
    container_name: web
    image: tracker/web:latest
    depends_on:
      - "backend"
    ports:
      - '80:80'
    build:
      context: Tracker.React
      dockerfile: Dockerfile
#      args:
#        NODE_ENV: development
#    env_file: Tracker.React/.env.development
#    environment:
#      NODE_ENV: development
  
  backend:
    image: tracker/backend:latest
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ConnectionStrings__PostgresConnection: host=db;port=5432;database=tracker;username=postgres;password=123123asd@

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123asd@
      - POSTGRES_DB=tracker
 
#  proxy:
#    image: nginx:mainline
#    volumes:
#      - ./Tracker.React/nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "80:80"  
     